version: "3.7"

services:
  api_exemplo_render:
    container_name: api_exemplo_render
    build:
      context: .
      dockerfile: Dockerfile
    image: api_exemplo_render
    ports:
      - "8075:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - FirebirdConnection=database=/var/lib/firebird/data/SUPER.fdb;user=SYSDBA;password=masterkey;datasource=firebird;port=3050
    depends_on:
      - firebird

  firebird:
    image: firebird/firebird:latest
    container_name: firebird
    ports:
      - "3050:3050"
    volumes:
      - ./data/SUPER.fdb:/var/lib/firebird/data/SUPER.fdb
    environment:
      - FIREBIRD_PASSWORD=masterkey
